name: WeatherApp

options:
  bundleIdPrefix: com.weatherapp.weatherapp
  deploymentTarget:
    iOS: 13.0
  preGenCommand: swiftgen
  groupOrdering:
    - order: [WeatherApp, SearchCity, CityList, WeatherDetails, UI, Core, Networking, Domain, Storage, Global, Resources]
    
targets:
  WeatherApp:
    type: application
    platform: iOS
    # devices: [iPhone, iPad]
    settings:
      base:
        SWIFT_VERSION: 5.5.2
        # TARGETED_DEVICE_FAMILY: 1
        CODE_SIGN_STYLE: "Manual"
        CURRENT_PROJECT_VERSION: 1
        VERSIONING_SYSTEM: "apple-generic"
        USE_SWIFT_RESPONSE_FILE: true
        OTHER_LDFLAGS: [-ObjC]
    info:
      path: WeatherApp/Supporting Files/Info.plist
      properties:
        UILaunchStoryboardName: "LaunchScreen"
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        CFBundleDisplayName: "Погода"
        CFBundleShortVersionString: "1.0.0"
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UIRequiresFullScreen: true
        CFBundleDevelopmentRegion: "ru"
        CFBundleLocalizations: ["ru"]
        ITSAppUsesNonExemptEncryption: false
    sources:
      - path: WeatherApp
      - path: Resources/Assets.xcassets
    dependencies:
      - target: Core
      - target: UI
      - target: CityList
      - target: SearchCity
      - target: WeatherDetails
      - target: Models
      - target: Global
      - target: Networking
      - target: Domain
      - target: Storage
      - target: Resources
      - package: SnapKit
      - package: IQKeyboardManagerSwift
      - package: RealmSwift

  Core:
    templates: 
      - Framework
    sources: [Core]
    info:
      path: Core/Supporting Files/Info.plist
      
  Global:
    templates:
      - Framework
    sources: [Global]
    info:
      path: Global/Supporting Files/Info.plist
      
  Networking:
    templates:
      - Framework
    sources: [Networking]
    info:
      path: Networking/Supporting Files/Info.plist
    dependencies:
      - target: Core
      - target: Storage
      - target: Domain
      - target: Global
      
  Storage:
    templates:
      - Framework
    sources: [Storage]
    info:
      path: Storage/Supporting Files/Info.plist
    dependencies:
      - target: Core
      - target: Domain
      - target: Models
      - package: RealmSwift

  Domain:
    templates:
      - Framework
    sources: [Domain]
    dependencies:
    - package: RealmSwift
    info:
      path: Domain/Supporting Files/Info.plist

  UI:
    templates: 
      - Framework
    sources: [UI]
    info:
      path: UI/Supporting Files/Info.plist
    dependencies:
      - target: Core
      - package: SnapKit
      - package: Kingfisher
      
  Resources:
    templates:
      - Framework
    sources: [Resources]
    info:
      path: Resources/Supporting Files/Info.plist
      
  Models:
    templates:
      - Framework
    sources: [Models]
    dependencies:
      - target: Domain
      - package: RealmSwift
    info:
      path: Models/Supporting Files/Info.plist

  CityList:
    templates:
      - Framework
    sources: [CityList]
    dependencies:
      - target: WeatherDetails
      - target: SearchCity
      - target: Core
      - target: UI
      - target: Storage
      - target: Networking
      - target: Models
      - package: SnapKit
      - package: RealmSwift
    info:
      path: CityList/Supporting Files/Info.plist
    
  SearchCity:
    templates:
      - Framework
    sources: [SearchCity]
    dependencies:
      - target: Core
      - target: UI
      - target: Networking
      - target: Models
      - package: SnapKit
      - package: RealmSwift
    info:
      path: SearchCity/Supporting Files/Info.plist
      
  WeatherDetails:
    templates:
      - Framework
    sources: [WeatherDetails]
    dependencies:
      - target: Core
      - target: UI
      - target: Storage
      - target: Networking
      - target: Models
      - package: SnapKit
      - package: RealmSwift
    info:
      path: WeatherDetails/Supporting Files/Info.plist

settings:
  base:
    TARGETED_DEVICE_FAMILY: 1
  configs:
    Debug:
      ENABLE_TESTABILITY: YES
      SWIFT_COMPILATION_MODE: singlefile
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      VALIDATE_PRODUCT: NO
    Release:
      ENABLE_TESTABILITY: NO
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
      VALIDATE_PRODUCT: YES

targetTemplates:
  Framework:
    type: framework
    platform: iOS
    deploymentTarget: 13.0
    settings:
      base:
        MARKETING_VERSION: 1.0
        SWIFT_VERSION: 5.5.2
        TARGETED_DEVICE_FAMILY: 1,2
        SUPPORTS_MACCATALYST: NO

packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit.git
    from: "5.6"
    
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    from: 7.0.0

  IQKeyboardManagerSwift:
    url: https://github.com/hackiftekhar/IQKeyboardManager.git
    from: 6.5.0
    
  RealmSwift:
    url: https://github.com/realm/realm-swift.git
    from: 10.28.6
